version: "3.9"

services:
  kafdrop:
    image: obsidiandynamics/kafdrop
    ports:
      - "9000:9000"
    environment:
      KAFKA_BROKER_CONNECT: "kafka:9092"
    depends_on:
      - kafka

  kafka:
    image: bitnami/kafka:3.5
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092,CONTROLLER://:9093
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9093
      ALLOW_PLAINTEXT_LISTENER: "yes"


  pub_100_mes_at_min:
    build:
      context: pub_100_mes_at_min
      dockerfile: Dockerfile
    container_name: pub_100_mes_at_min
    environment:
      KAFKA_BROKER: kafka:9092
      MONGODB_COLLECTION: tweets
      MONGODB_USER: IRGC_NEW
      MONGODB_PASSWORD: iran135
      MONGODB_DATABASE: IranMalDB
    ports:
      - "8002:8002"
    depends_on:
      - kafka

volumes:
  mongo_data:
