apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-retrieval
spec:
  replicas: 1
  selector:
    matchLabels:
      app: data-retrieval
  template:
    metadata:
      labels:
        app: data-retrieval
    spec:
      containers:
      - name: data-retrieval
        image: yakovthedocker/data-retrieval:1.1
        ports:
        - containerPort: 8004
        env:
          - name: MONGODB_HOST
            value: mongodb
          - name: MONGODB_USER
            value: "admin"
          - name: MONGODB_PASSWORD
            value: "yakov"
          - name: MONGODB_DATABASE
            value: "tweets"
          - name: MONGODB_AUTH_DB
            value: "admin"
          - name: MONGODB_PORT
            value: "27017"
