apiVersion: apps/v1
kind: Deployment
metadata:
  name: processor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: processor
  template:
    metadata:
      labels:
        app: processor
    spec:
      containers:
      - name: pub_100
        image: yakovthedocker/processor:1.1
        ports:
        - containerPort: 8001
        env:
          - name: KAFKA_BROKER
            value: "kafka:9092"

